"""service category

Revision ID: 4e6c9f00e7ca
Revises: c19d42a5456f
Create Date: 2026-08-01 10:09:12.309888

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '4e6c9f00e7ca'
down_revision: str | None = 'c19d42a5456f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate doesn't emit CREATE TYPE for a brand new enum used only in
    # add_column - create it explicitly first, or the ALTER TABLE below 404s.
    service_category = postgresql.ENUM(
        'streaming', 'music', 'cloud_storage', 'productivity', 'gaming', 'ai',
        'education', 'utilities', 'shopping', 'social', 'other',
        name='service_category',
    )
    service_category.create(op.get_bind(), checkfirst=True)
    op.add_column('services', sa.Column('category', service_category, server_default='other', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'category')
    # ### end Alembic commands ###
    postgresql.ENUM(name='service_category').drop(op.get_bind(), checkfirst=True)
