"""initial schema

Revision ID: 6dd9d8174eaa
Revises: 
Create Date: 2026-07-31 19:07:39.569487

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6dd9d8174eaa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_patterns', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cancel_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('base_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('reminder_policy', sa.Enum('off', 'days_before', 'weekly_digest', 'monthly_report', name='reminder_policy'), server_default='off', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('gmail', 'imap', name='email_provider'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'error', 'disconnected', name='email_account_status'), server_default='active', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_accounts')),
    sa.UniqueConstraint('user_id', 'email', name=op.f('uq_email_accounts_user_id'))
    )
    op.create_index(op.f('ix_email_accounts_user_id'), 'email_accounts', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period', sa.Enum('weekly', 'monthly', 'quarterly', 'yearly', name='subscription_period'), nullable=False),
    sa.Column('next_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'cancelled', name='subscription_status'), server_default='active', nullable=False),
    sa.Column('source', sa.Enum('manual', 'email', name='subscription_source'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_subscriptions_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_next_charge_at'), 'subscriptions', ['next_charge_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_service_id'), 'subscriptions', ['service_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('off', 'days_before', 'weekly_digest', 'monthly_report', name='reminder_kind'), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_reminders_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_fire_at'), 'reminders', ['fire_at'], unique=False)
    op.create_index(op.f('ix_reminders_subscription_id'), 'reminders', ['subscription_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], name=op.f('fk_transactions_email_account_id_email_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_transactions_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('email_account_id', 'message_id', name=op.f('uq_transactions_email_account_id'))
    )
    op.create_index(op.f('ix_transactions_email_account_id'), 'transactions', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_subscription_id'), 'transactions', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_subscription_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_email_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reminders_subscription_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_fire_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_service_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_charge_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_email_accounts_user_id'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
    # Native Postgres ENUM types are not dropped automatically when the
    # tables that reference them are dropped - remove them explicitly so
    # downgrade leaves a truly clean database.
    postgresql.ENUM(name='reminder_kind').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='subscription_source').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='subscription_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='subscription_period').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='email_account_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='email_provider').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='reminder_policy').drop(op.get_bind(), checkfirst=True)
