"""subscription is_recurring flag

Revision ID: 7779432b41ba
Revises: e9397fe3f8e2
Create Date: 2026-08-01 12:11:10.418269

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7779432b41ba'
down_revision: str | None = 'e9397fe3f8e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_recurring')
    # ### end Alembic commands ###
