"""reminders: user_id, nullable subscription_id

Revision ID: c19d42a5456f
Revises: 6dd9d8174eaa
Create Date: 2026-07-31 19:50:43.630665

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c19d42a5456f'
down_revision: str | None = '6dd9d8174eaa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('reminders', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_reminders_user_id_users'), 'reminders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reminders_user_id_users'), 'reminders', type_='foreignkey')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.alter_column('reminders', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reminders', 'user_id')
    # ### end Alembic commands ###
