"""unique email subscription per user+service or name

Revision ID: e9397fe3f8e2
Revises: 4e6c9f00e7ca
Create Date: 2026-08-01 11:27:02.667356

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e9397fe3f8e2'
down_revision: str | None = '4e6c9f00e7ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
